# Generated by Django 4.2.7 on 2023-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_verifieduser_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
