# Generated by Django 4.2.7 on 2023-11-29 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_comments_userrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='date_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
