# Generated by Django 4.2.7 on 2023-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_listed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
